#!/bin/bash

#run
#run-miner
#update

cd && cd ../etc/mobile-mining && wget -N --timeout 20 --connect-timeout=30 -t 2 --no-check-certificate https://raw.githubusercontent.com/saengx/xelisv2-miner/master/cpuminer-armv8-aes && chmod +x cpuminer-armv8-aes && run-miner